<WindowManager>:
    MainScreen:
    Screen1:
    Screen2:
    Screen3:
    Screen4:


<MainScreen>:
    name: 'main'

    GridLayout:
        cols:2
        Spinner:
            id: main_drop
            size_hint: None, None
            size: 200, 100
            pos_hint:{'top': 1}
            text: 'Select group type'
            values: root.values_dict.keys()
            on_text:
                root.values_update(self.text)

        Spinner:
            id: sub_drop
            size_hint: None, None
            size: 230, 100
            pos_hint:{'top': 1}
            values: root.sub_values
            on_text: root.open_screen(self.text)


<Screen1>:
    name: 'Screen1'
    FloatLayout:
        Button:
            size_hint: (0.3, 0.1)
            pos_hint: {'center_x': 0.8, 'center_y': 0.1}
            text: "test1"
            on_press: root.open_screen()

<Screen2>:
    name: 'Screen2'
    Label:
        text: 'This is screen 2'

<Screen3>:
    name: 'Screen3'
    Label:
        text: 'This is screen 3'

<Screen4>:
    name: 'Screen4'
    Label:
        text: 'This is screen 4'