

<WindowManager>:
    MainScreen:
    ResultScreen:
    ThirdScreen:
    InfoScreen:

<MainScreen>:
    name:'main'
    canvas.before:
        Rectangle:
            pos: self.pos
            size: self.size
            source: "testlogo.jpg"
    GridLayout:
        cols:2
        pos_hint: {"top": 0.85, "right": 1.25}
        Spinner:
            id: main_drop
            size_hint: None, None
            size: 180, 50
            pos_hint:{'top': 1}
            text: '도시 선택'
            font_name: './HMKMRHD.ttf'
            option_cls: 'MySpinnerOption'
            values: root.values_dict.keys()
            on_text:
                root.values_update(self.text)

        Spinner:
            id: sub_drop
            size_hint: None, None
            size: 180, 50
            pos_hint:{'top': 1}
            text: '시/군/구 선택'
            font_name: './HMKMRHD.ttf'
            option_cls: 'MySpinnerOption'
            values: root.sub_values

            
    FloatLayout:
        Button:
            size_hint: (0.3, 0.1)
            pos_hint: {'center_x': 0.8, 'center_y': 0.1}
            text: "제출"
            font_name: './HMKMRHD.ttf'
            on_press:
                root.convert2r()
                root.manager.get_screen('result').ids.CityState.text = root.ids.main_drop.text + '-' + root.ids.sub_drop.text
                
                

            
        Button:
            size_hint: (0.3, 0.1)
            pos_hint: {'center_x': 0.2, 'center_y': 0.1}
            text: "종료"
            font_name: './HMKMRHD.ttf'
            on_press: root.onExit()
    

<ResultScreen>:
    name:'result'
    canvas.before:
        Rectangle:
            pos: self.pos
            size: self.size
            source: "testlogo.jpg"


    
    GridLayout:
        cols: 4
        size_hint: 1, 0.2
        pos_hint: {"top": 0.9, "right": 1}
        canvas.before:
            Color:
                rgba: 0.2, 0.2, 0.2, 0.8
            Rectangle:
                pos: self.pos
                size: self.size

        Label:
            id:key1
            text: '키워드1'
            font_name: './HMKMRHD.ttf'
            text_size: self.size
            valign: 'middle'

        CheckBox:
            id : chk_key1

        Label:
            id:key2
            text: '키워드2'
            font_name: './HMKMRHD.ttf'
            text_size: self.size
            valign: 'middle'

        CheckBox:
            id: chk_key2      
        
        Label:
            id:key3
            text: '키워드3'
            font_name: './HMKMRHD.ttf'
            text_size: self.size
            valign: 'middle'

        CheckBox:
            id: chk_key3

        Label:
            id:key4
            text: '키워드4'
            font_name: './HMKMRHD.ttf'
            text_size: self.size
            valign: 'middle'

        CheckBox:
            id: chk_key4   
        
        Label:
            id:key5
            text: '키워드5'
            font_name: './HMKMRHD.ttf'
            text_size: self.size
            valign: 'middle'

        CheckBox:
            id: chk_key5  
        
        Label:
            id:key6
            text: '키워드6'
            font_name: './HMKMRHD.ttf'
            text_size: self.size
            valign: 'middle'

        CheckBox:
            id: chk_key6  
        
        Label:
            id:key7
            text: '키워드7'
            font_name: './HMKMRHD.ttf'
            text_size: self.size
            valign: 'middle'

        CheckBox:
            id: chk_key7  
        
        Label:
            id:key8
            text: '키워드8'
            font_name: './HMKMRHD.ttf'
            text_size: self.size
            valign: 'middle'

        CheckBox:
            id: chk_key8  
        
        Label:
            id:key9
            text: '키워드9'
            font_name: './HMKMRHD.ttf'
            text_size: self.size
            valign: 'middle'

        CheckBox:
            id: chk_key9

        Label:
            id:key10
            text: '키워드10'
            font_name: './HMKMRHD.ttf'
            text_size: self.size
            valign: 'middle'

        CheckBox:
            id: chk_key10      



    GridLayout:
        id: recom
        rows: 5
        size_hint: 1, 0.55
        pos_hint: {"top": 0.7, "right": 1}
        disabled: True
        Button:
            canvas.before:
                Color:
                    rgba: 0.2, 0.2, 0.2, 0.8
                Rectangle:
                    pos: self.pos
                    size: self.size
            id: recom1
            text: "첫번째 추천지역 ->"
            font_name: './HMKMRHD.ttf'
            on_press: root.convert2t(self.text)
            

        Button:
            canvas.before:
                Color:
                    rgba: 0.2, 0.2, 0.2, 0.8
                Rectangle:
                    pos: self.pos
                    size: self.size
            id: recom2
            text: "두번째 추천지역 ->"
            font_name: './HMKMRHD.ttf'
            on_press: root.convert2t(self.text)    

        Button:
            canvas.before:
                Color:
                    rgba: 0.2, 0.2, 0.2, 0.8
                Rectangle:
                    pos: self.pos
                    size: self.size
            id: recom3
            text: "세번째 추천지역 ->"
            font_name: './HMKMRHD.ttf'
            on_press: root.convert2t(self.text) 

        Button:
            canvas.before:
                Color:
                    rgba: 0.2, 0.2, 0.2, 0.8
                Rectangle:
                    pos: self.pos
                    size: self.size
            id: recom4
            text: "네번째 추천지역 ->"
            font_name: './HMKMRHD.ttf'
            on_press: root.convert2t(self.text) 

        Button:
            canvas.before:
                Color:
                    rgba: 0.2, 0.2, 0.2, 0.8
                Rectangle:
                    pos: self.pos
                    size: self.size
            id: recom5
            text: "다섯번째 추천지역 ->"
            font_name: './HMKMRHD.ttf'
            on_press: root.convert2t(self.text) 

    FloatLayout:
        Button:
            size_hint: (0.3, 0.1)
            pos_hint: {'center_x': 0.2, 'center_y': 0.1}
            text: "메인화면으로"
            font_name: './HMKMRHD.ttf'
            background_color: 0.2, 0.2, 0.5, 0.8   
            on_press: root.convert2m()

        Button:
            size_hint: (0.3, 0.1)
            pos_hint: {'center_x': 0.8, 'center_y': 0.1}
            text: "추천지역 보기"
            font_name: './HMKMRHD.ttf'
            background_color: 0.2, 0.2, 0.5, 0.8   
            on_press: 
                root.get_keyval()


        
        Label:
            canvas.before:
                Color:
                    rgba: 0.2, 0.2, 0.5, 0.8     
                Rectangle:
                    pos: self.pos
                    size: self.size
            id: CityState
            text: ''
            font_name: './HMKMRHD.ttf'
            size_hint: 1, 0.1
            pos_hint: {'top':1, 'right': 1}

    #    Spinner:
    #       id: resource
    #        size_hint: None, None
    #        size: 200, 50
    #        pos_hint:{'top': 0.95, 'right': 0.6}
    #        text: 'Select Resource'
    #        values: root.resource_value



<ThirdScreen>:
    name:'third'
    canvas.before:
        Rectangle:
            pos: self.pos
            size: self.size
            source: "testlogo.jpg"  

#    ScrollView:
#        do_scroll_x: False
#        do_scroll_y: True
#        pos_hint: {'top': 0.85}
#        Label:
#            canvas.before:
#                Color:
#                    rgba: 0.2, 0.2, 0.2, 0.8
#                Rectangle:
#                    pos: self.pos
#                    size: self.size
#            text:'관광지 설명'
#            font_name: './HMKMRHD.ttf'
#            pos_hint: {'right':1}

    GridLayout:
        id: tourrec
        rows: 5
        size_hint: 0.75, 0.2
        pos_hint: {"top": 0.85, "right": 0.75}
        Label:
            canvas.before:
                Color:
                    rgba: 0.2, 0.2, 0.2, 0.8
                Rectangle:
                    pos: self.pos
                    size: self.size
            id: tourrecom1
            text: "주요관광지1 ->"
            font_name: './HMKMRHD.ttf'    
        Label:
            canvas.before:
                Color:
                    rgba: 0.2, 0.2, 0.2, 0.8
                Rectangle:
                    pos: self.pos
                    size: self.size
            id: tourrecom2
            text: "주요관광지2 ->"
            font_name: './HMKMRHD.ttf'   

        Label:
            canvas.before:
                Color:
                    rgba: 0.2, 0.2, 0.2, 0.8
                Rectangle:
                    pos: self.pos
                    size: self.size
            id: tourrecom3
            text: "주요관광지3 ->"
            font_name: './HMKMRHD.ttf'

        Label:
            canvas.before:
                Color:
                    rgba: 0.2, 0.2, 0.2, 0.8
                Rectangle:
                    pos: self.pos
                    size: self.size
            id: tourrecom4
            text: "주요관광지4 ->"
            font_name: './HMKMRHD.ttf' 

        Label:
            canvas.before:
                Color:
                    rgba: 0.2, 0.2, 0.2, 0.8
                Rectangle:
                    pos: self.pos
                    size: self.size
            id: tourrecom5
            text: "주요관광지5 ->"
            font_name: './HMKMRHD.ttf' 
    FloatLayout:
        Label:
            canvas.before:
                Color:
                    rgba: 0.2, 0.2, 0.5, 0.8
                Rectangle:
                    pos: self.pos
                    size: self.size
            id: CityState2
            text: ""
            font_name: './HMKMRHD.ttf'
            size_hint: 1, 0.1
            pos_hint: {'top':1, 'right': 1}
        Label:
            canvas.before:
                Color:
                    rgba: 0.2, 0.2, 0.3, 0.6
                Rectangle:
                    pos: self.pos
                    size: self.size
            text: "주요 관광지"
            font_name: './HMKMRHD.ttf'
            size_hint: 0.75, 0.05
            pos_hint: {'top':0.9, 'right': 0.75}

        Button:
            background_color: (0.2, 0.5, 0.8, 0.8)
            id: ttrecom1
            size_hint: (0.2, 0.04)
            pos_hint: {"top": 0.85, "right": 0.95}
            text: "111 ->"
            on_press:
                root.convert2i()

        Button:
            background_color: (0.2, 0.5, 0.8, 0.8)
            id: ttrecom1
            size_hint: (0.2, 0.04)
            pos_hint: {"top": 0.81, "right": 0.95}
            text: "222 ->"
            on_press:
                root.convert2i()

        Button:
            background_color: (0.2, 0.5, 0.8, 0.8)
            id: ttrecom1
            size_hint: (0.2, 0.04)
            pos_hint: {"top": 0.77, "right": 0.95}
            text: "333 ->"
            on_press:
                root.convert2i()

        Button:
            background_color: (0.2, 0.5, 0.8, 0.8)
            id: ttrecom1
            size_hint: (0.2, 0.04)
            pos_hint: {"top": 0.73, "right": 0.95}
            text: "444 ->"
            on_press:
                root.convert2i()
        
        Button:
            background_color: (0.2, 0.5, 0.8, 0.8)
            id: ttrecom1
            size_hint: (0.2, 0.04)
            pos_hint: {"top": 0.69, "right": 0.95}
            text: "555 ->"
            on_press:
                root.convert2i()             

        Button:
            background_color: (0.2, 0.5, 0.8, 0.8)
            text:'메인화면으로'
            font_name: './HMKMRHD.ttf'
            size_hint:(0.5, 0.1)
            pos_hint: {'center_x': 0.25, 'center_y': 0.1}
            on_press: root.convert2m()

        Button:
            background_color: (0.2, 0.5, 0.8, 0.6)
            text:'이전화면으로'
            font_name: './HMKMRHD.ttf'
            size_hint:(0.5, 0.1)
            pos_hint: {'center_x': 0.75, 'center_y': 0.1}
            on_press: root.convert2r() 

<InfoScreen>:
    name: 'info'
    canvas.before:
        Rectangle:
            pos: self.pos
            size: self.size
            source: "testlogo.jpg"  
    Label:
        canvas.before:
            Color:
                rgba: 0.2, 0.2, 0.2, 0.8     
            Rectangle:
                pos: self.pos
                size: self.size
        id: rectourname
        text: 'test'
        font_name: './HMKMRHD.ttf'
        size_hint: 1, 0.1
        pos_hint: {'top':1, 'right': 1}
